version: 2.1

workflows:
  test-env-vars:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "echo an env var that is part of our project"
          environment:
            OWNER_NAME_SET_IN_CIRCLECI: Name is ${OWNER_NAME}
          command: |
            echo $OWNER_NAME_SET_IN_CIRCLECI
